language: java
sudo: false
branches:
  only:
  - master
  - html
addons:
  apt:
    packages:
    - lib32stdc++6
    - lib32z1
    - unzip
jdk:
- openjdk8
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_install:
- 'if [ "$TRAVIS_SECURE_ENV_VARS" = "true" ]; then openssl aes-256-cbc -K $encrypted_149d500ec6e2_key -iv $encrypted_149d500ec6e2_iv -in build.properties.enc -out build.properties -d; fi'
- git fetch --unshallow
- git checkout -qf $TRAVIS_COMMIT
- echo $TRAVIS_COMMIT
- android/travis_androidsdk.sh
install: true
script: ./gradlew travis --max-workers 1
after_failure: find . -name androidsdk -prune -o -print
